language: python

dist: xenial

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt update
  - sudo apt install libfftw3-dev libav-tools ffmpeg

install:
  - "cd .."
  - "git clone https://github.com/MTG/essentia"
  - "cd essentia"
  - "./waf configure --build-static --with-python"
  - "./waf"
  - "./waf install"
  - "cd ../IzunaDSP"
  - "pip install -r requirements-ci.txt"

script:
  # ignore output from install
  - python setup.py install >> /dev/null
  - snekchek

cache:
  - pip

notifications:
  email: false
