language: python

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt update
  - sudo apt install libfftw3-dev libav-tools ffmpeg

install:
  - pip install -r requirements-ci.txt

script:
  - snekchek
  - python setup.py install
  - pytest

cache:
  - pip

notifications:
  email: false
